name: scipy-lecture
dependencies:
  - pip
  - nose
  - pillow
  - Sphinx
  - python=2
  - numpy=1.9
  - scipy=0.14.0
  - matplotlib=1.4.0
  - scikit-learn=0.16.1
  - sympy=0.7.5
  - scikit-image=0.10.1
  - pandas=0.15
  - seaborn=0.6
  - statsmodels=0.5

